name: Build project
on:
  push:
    branches:
      - master
jobs:
  build-linux:
    name: Build Server (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get install -y gcc-multilib g++-multilib python3-pip

      - name: Install Conan
        run: pip3 install "conan<2.0"

      - name: Configure and Build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-fpermissive -I$PWD/server/third-party/omp-sdk/include"
          cmake --build build --config Release --parallel

      - name: Upload Server Artifact
        uses: actions/upload-artifact@v6
        with:
          name: linux
          path: build/server/*.so

  build-windows:
    name: Build Client & Server (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Checkout Plugin-SDK
        uses: actions/checkout@v6
        with:
          repository: DK22Pac/plugin-sdk
          path: plugin-sdk

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Patch Conan CMake for MSVC 194x
        run: |
           python -c "path='server/third-party/omp-sdk/lib/cmake-conan/conan.cmake'; content=open(path, 'r').read(); open(path, 'w').write(content.replace('VERSION_LESS 1940', 'VERSION_LESS 1950'))"

      - name: Install Conan
        run: pip install "conan<2.0"

      - name: Build Plugin-SDK
        shell: cmd
        run: |
          cd plugin-sdk
          set PLUGIN_SDK_DIR=%CD%
          tools\premake\premake5.exe --file=tools\premake\premake5.lua --pluginsdkdir="%CD%" vs2022
          msbuild plugin.sln /p:Configuration=Release
          
      - name: Configure and Build
        env:
          PLUGIN_SDK_DIR: ${{ github.workspace }}/plugin-sdk
        run: |
          cmake -B build -A Win32 -DCMAKE_BUILD_TYPE=Release -DBUILD_CLIENT=ON
          cmake --build build --config Release --parallel

      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: windows
          path: |
            build/server/**/*.dll
            build/client/**/*.dll
          
        