name: Build project
on:
  push:
    branches:
      - master
jobs:
  build-linux:
    name: Build Server (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get install -y gcc-multilib g++-multilib python3-pip

      - name: Install Conan
        run: pip3 install "conan<2.0"

      - name: Configure and Build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-fpermissive"
          cmake --build build --config Release --parallel

      - name: Upload Server Artifact
        uses: actions/upload-artifact@v6
        with:
          name: linux
          path: build/server/*.so

  build-windows:
    name: Build Client & Server (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Checkout Plugin-SDK
        uses: actions/checkout@v6
        with:
          repository: DK22Pac/plugin-sdk
          path: plugin-sdk

      - name: Build Plugin-SDK
        run: |
          cmake -S plugin-sdk -B plugin-sdk/build -A Win32 -DCMAKE_BUILD_TYPE=Release
          cmake --build plugin-sdk/build --config Release --parallel
          mkdir plugin-sdk/output/lib
          cp plugin-sdk/build/Release/*.lib plugin-sdk/output/lib/

      - name: Configure and Build
        env:
          PLUGIN_SDK_DIR: ${{ github.workspace }}/plugin-sdk
        run: |
          cmake -B build -A Win32 -DCMAKE_BUILD_TYPE=Release -DBUILD_CLIENT=ON
          cmake --build build --config Release --parallel

      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: windows
          path: |
            build/server/**/*.dll
            build/client/**/*.dll
          
        